female("Grace").
female("DeDe").
female("Gloria").
female("Barb").
female("Claire").
female("Cameron").
female("Bo").
female("Haley").
female("Lily").
female("Poppy").

male("Rexford").
male("George").
male("Calhoun").
male("Alex").
male("Luke").
male("Dylan").
male("Pameron").
male("Mitchell").
male("Joe").
male("Many").
male("Phil").
male("Javier").
male("Merle").
male("Jay").
male("Frank").

% a is b's parent 
parent("Grace","Phil").
parent("Frank","Phil").
parent("DeDe","Claire").
parent("Jay","Claire").
parent("Jay","Mitchell").
parent("DeDe","Mitchell").
parent("Jay","Joe").
parent("Gloria","Joe").
parent("Gloria","Many").
parent("Javier","Many").
parent("Barb","Cameron").
parent("Merle","Cameron").
parent("Barb","Pameron").
parent("Merle","Pameron").
parent("Phil","Haley").
parent("Claire","Haley").
parent("Phil","Alex").
parent("Claire","Alex").
parent("Phil","Luke").
parent("Claire","Luke").
parent("Mitchell","Lily").
parent("Cameron","Lily").
parent("Mitchell","Rexford").
parent("Cameron","Rexford").
parent("Bo","Calhoun").
parent("Pameron","Calhoun").
parent("Dylan","George").
parent("Haley","George").
parent("Dylan","Poppy").
parent("Haley","Poppy").